name=LM75_AB
version=1.0.0
author=Norman Dunbar <norman@dunbar-it.co.uk>
maintainer=Norman Dunbar <norman@dunbar-it.co.uk>
sentence=LM75A/LM75B temperature sensor routines for Arduino C/C++ code.
paragraph=This library provides various functions for use with an LM75A/LM75B temperature sensor in Arduino sketches on ATmega328P and similar AVR/Microchip microcontrollers.
category=Sensors
url=https://github.com/NormanDunbar/LM75_AB
depends=Wire
includes=LM75_AB.h
architectures=avr
dot_a_linkage=true
